modLoader="javafml"
loaderVersion="[39,)"
license="MIT License"
[[mods]]
modId="beyond_earth"
version="${file.jarVersion}"
displayName="Beyond Earth"
credits="mrscauthd"
authors="mrscauthd"
description=''''''
[[dependencies.beyond_earth]]
    modId="forge"
    mandatory=true
    versionRange="[39.0.63,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.beyond_earth]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.beyond_earth]]
    modId="beyond_earth"
    mandatory=true
    versionRange="[6.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.beyond_earth]]
    modId="tconustruct"
    mandatory=false
    versionRange="[3.4.1.46,)"
    ordering="AFTER"
    side="BOTH"
